export const GET_TASKS_START = 'GET_TASKS_START';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_NEXT_LEVEL_TASKS_START = 'GET_NEXT_LEVEL_TASKS_START';
export const GET_NEXT_LEVEL_TASKS_SUCCESS = 'GET_NEXT_LEVEL_TASKS_SUCCESS';
